### ISSUE TITLE
OSError: [Errno 39] Directory not empty: '/tmp/pymp-yffyhr_a'

### ISSUE THREAD

**Issue by HKLee2040** [renqianluo/NAO_pytorch#3]
When I run the script "train_search_cifar10.sh", I got the following error message:
Is there anyone meet the same problem?

06/26 04:36:37 AM epoch 200 lr 1.001480e-03
06/26 04:37:52 AM Train 100 loss 8.535959e-01 top1 69.921875 top5 97.640625
06/26 04:37:52 AM Arch: 0 3 1 1 0 3 0 1 0 3 0 1 0 1 2 1 1 0 0 2 0 2 0 2 0 2 0 2 1 2 2 1 1 2 1 2 0 1 1 4
06/26 04:39:07 AM Train 200 loss 8.636655e-01 top1 69.648438 top5 97.507812
06/26 04:39:07 AM Arch: 1 0 1 0 2 0 2 2 0 2 3 0 2 0 3 0 5 1 5 3 1 0 1 0 1 0 2 0 2 4 2 0 3 0 4 0 3 0 5 1
06/26 04:40:24 AM Train 300 loss 8.717919e-01 top1 69.536461 top5 97.359375
06/26 04:40:24 AM Arch: 0 0 0 4 2 1 0 4 3 2 2 3 1 0 3 3 1 1 2 0 1 4 0 1 1 4 0 4 2 0 3 4 1 2 0 3 2 4 5 3
06/26 04:41:40 AM Train 400 loss 8.707097e-01 top1 69.695312 top5 97.453125
06/26 04:41:40 AM Arch: 0 1 1 4 2 4 1 4 3 3 0 4 4 1 3 4 2 1 3 1 0 1 1 0 2 4 2 1 0 4 2 1 2 1 4 4 0 1 3 3
06/26 04:42:56 AM Train 500 loss 8.609787e-01 top1 69.934380 top5 97.509377
06/26 04:42:56 AM Arch: 0 2 1 3 2 1 0 1 3 0 1 1 1 3 0 2 3 1 0 1 1 2 1 1 1 0 0 0 0 2 3 0 0 1 2 2 1 3 4 1
06/26 04:44:14 AM Train 600 loss 8.675684e-01 top1 69.739586 top5 97.424484
06/26 04:44:14 AM Arch: 0 1 1 1 0 1 1 1 0 1 0 1 3 1 3 1 1 1 1 3 1 1 1 1 1 3 0 1 1 1 0 1 4 1 3 3 1 1 2 0
06/26 04:45:30 AM Train 700 loss 8.684698e-01 top1 69.627228 top5 97.437500
06/26 04:45:30 AM Arch: 0 2 0 4 1 1 0 1 3 1 0 3 3 1 3 3 1 2 0 3 1 2 1 3 1 3 1 2 2 3 2 2 2 0 1 2 1 2 0 0
06/26 04:45:34 AM train_acc 69.608887
06/26 04:46:40 AM Valid arch 0 1 0 3 1 3 0 3 1 3 0 0 3 1 3 1 5 1 2 2 1 0 1 0 2 3 1 0 1 4 0 4 3 2 2 0 1 1 2 0
 loss 0.73 top1 74.000000 top5 97.800003
06/26 04:47:46 AM Valid arch 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 loss 0.72 top1 76.400002 top5 97.800003
06/26 04:48:54 AM Valid arch 1 1 1 4 0 4 0 2 1 3 0 4 3 1 1 4 0 1 1 3 1 3 1 1 1 2 0 2 0 2 0 2 0 4 1 1 0 4 1 4
 loss 0.85 top1 70.599998 top5 98.200005
06/26 04:50:00 AM Valid arch 0 0 1 2 2 3 0 0 1 4 2 3 3 2 2 3 4 2 4 1 1 3 1 4 1 3 1 2 3 3 3 1 3 2 3 3 1 1 2 4
 loss 0.94 top1 68.000000 top5 98.000000
06/26 04:51:06 AM Valid arch 0 0 1 1 0 0 2 1 0 2 3 0 2 1 2 0 2 2 3 1 0 1 1 1 1 2 1 2 3 1 2 1 2 1 2 1 2 1 4 1
 loss 0.82 top1 74.599998 top5 97.400002
06/26 04:52:10 AM Valid arch 0 0 0 3 1 2 0 3 2 2 3 4 4 2 2 0 2 4 1 0 0 1 0 0 2 3 2 1 0 0 2 4 1 4 3 0 3 1 4 2
 loss 0.78 top1 71.000000 top5 98.000000
06/26 04:53:15 AM Valid arch 0 1 1 0 1 2 2 0 0 3 3 2 1 3 2 4 2 4 4 1 0 3 1 4 2 4 1 1 0 3 3 0 1 2 0 2 2 0 4 2
 loss 0.87 top1 69.800003 top5 97.400002
06/26 04:54:19 AM Valid arch 0 0 0 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 0 0 0 0 0 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0
 loss 0.79 top1 70.400002 top5 98.200005
06/26 04:55:22 AM Valid arch 1 2 0 0 0 2 0 2 2 1 2 4 1 4 4 2 1 0 4 3 1 0 1 0 0 0 0 4 3 2 0 2 1 0 0 4 5 1 4 2
 loss 0.94 top1 66.800003 top5 97.200005
06/26 04:56:26 AM Valid arch 1 0 1 3 0 2 2 4 0 1 1 2 4 1 1 4 1 3 1 1 0 0 0 4 2 4 2 2 3 3 2 3 2 4 0 2 0 1 1 1
 loss 0.88 top1 69.000000 top5 97.200005
06/26 04:57:29 AM Valid arch 1 0 1 0 1 0 1 2 3 3 2 1 3 3 4 2 1 0 1 2 0 1 0 2 1 0 2 2 0 2 2 3 2 2 4 4 4 3 3 3
 loss 1.08 top1 64.800003 top5 96.200005
Traceback (most recent call last):
  File "/home/walker/anaconda3/envs/py35/lib/python3.5/multiprocessing/util.py", line 262, in _run_finalizers
    finalizer()
  File "/home/walker/anaconda3/envs/py35/lib/python3.5/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/walker/anaconda3/envs/py35/lib/python3.5/shutil.py", line 484, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/home/walker/anaconda3/envs/py35/lib/python3.5/shutil.py", line 482, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/tmp/pymp-yffyhr_a'
06/26 04:58:32 AM Valid arch 0 4 0 1 2 4 2 1 3 0 2 2 3 0 1 2 1 2 5 0 0 2 1 4 1 4 0 4 3 0 3 4 4 1 3 1 0 2 5 0
 loss 0.90 top1 68.599998 top5 96.000000
06/26 04:59:35 AM Valid arch 1 1 1 2 0 4 1 2 2 2 3 1 0 0 1 1 5 1 5 2 0 1 0 3 2 1 2 1 3 3 3 2 3 1 2 2 0 1 3 3
 loss 1.19 top1 59.799999 top5 94.000000
06/26 05:00:42 AM Valid arch 0 2 1 4 1 2 2 1 3 0 2 3 2 2 4 1 5 1 4 0 1 0 0 0 1 1 1 1 2 3 3 4 2 3 2 0 5 0 0 1
 loss 1.90 top1 21.200001 top5 82.200005
06/26 05:01:44 AM Valid arch 0 1 0 1 0 2 0 2 0 3 0 2 1 3 4 3 0 0 4 4 0 3 0 1 0 0 0 1 0 2 1 0 1 1 4 0 5 3 3 4
 loss 0.79 top1 74.200005 top5 98.000000
06/26 05:02:47 AM Valid arch 0 0 0 0 0 0 0 4 0 4 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 2 0 0 2 0 0 0
 loss 0.74 top1 73.800003 top5 97.599998
06/26 05:03:51 AM Valid arch 0 3 1 1 2 1 0 1 0 2 2 4 0 1 0 4 4 4 1 1 0 1 1 1 0 1 1 1 2 3 3 3 3 1 2 1 1 2 4 4
 loss 0.89 top1 67.599998 top5 98.000000
06/26 05:04:52 AM Valid arch 0 2 0 3 1 4 1 0 0 1 0 1 2 2 2 0 3 1 2 3 1 3 1 1 0 1 0 4 2 3 1 0 3 3 1 4 1 2 5 3
 loss 0.89 top1 69.599998 top5 97.200005

**Comment by xiaoshingshing** [comment]
It seems that top1 acc on cifar-10 is below 80%.  Anything wrong?

**Comment by kl2005ad** [comment]
I got similar problem :

09/23 03:24:32 PM train_acc 72.453331
09/23 03:29:45 PM Valid arch 0 0 0 4 0 1 2 3 3 4 2 4 1 0 0 4 5 0 1 4 1 4 0 2 0 3 2 1 3 2 0 0 2 4 3 1 2 1 3 2
 loss 0.90 top1 69.200005 top5 97.599998
09/23 03:34:57 PM Valid arch 0 1 0 1 0 3 2 0 2 0 0 1 4 1 0 0 1 1 0 0 0 0 1 3 0 0 2 0 0 3 0 1 1 2 4 0 4 1 4 0
 loss 1.32 top1 55.799999 top5 94.400002
09/23 03:40:11 PM Valid arch 0 1 0 2 0 1 2 2 0 3 0 0 1 3 4 0 0 3 1 3 1 1 0 0 0 1 2 4 1 0 2 3 3 1 0 2 0 2 0 2
 loss 0.82 top1 74.800003 top5 97.200005
09/23 03:45:23 PM Valid arch 0 1 0 4 2 2 2 4 1 4 1 2 1 0 4 4 5 3 5 1 0 3 1 0 0 1 2 4 1 2 1 2 0 2 2 2 5 1 0 3
 loss 1.00 top1 66.599998 top5 95.200005
09/23 03:50:36 PM Valid arch 1 0 0 3 0 4 2 4 0 1 0 4 0 2 0 1 1 1 3 1 0 2 0 0 0 0 0 2 0 3 0 2 0 1 2 0 3 4 0 0
 loss 1.25 top1 56.400002 top5 93.000000
09/23 03:55:47 PM Valid arch 1 4 1 3 0 0 1 2 0 3 2 4 3 3 3 1 0 1 4 3 0 2 0 1 2 2 0 2 2 4 2 4 0 1 3 0 2 2 4 3
 loss 1.42 top1 54.600002 top5 94.599998
09/23 04:00:59 PM Valid arch 0 4 1 4 1 0 0 1 3 4 1 4 0 3 2 2 1 3 4 3 0 3 1 1 1 0 2 4 1 3 0 1 1 3 1 4 2 3 3 0
 loss 0.96 top1 65.599998 top5 96.400002
09/23 04:06:09 PM Valid arch 1 2 1 4 0 4 0 2 2 1 1 0 2 1 0 0 2 1 0 2 1 3 0 0 1 2 0 4 2 0 3 3 2 0 3 3 2 3 0 3
 loss 1.43 top1 50.200001 top5 92.000000
09/23 04:11:20 PM Valid arch 1 3 0 1 1 1 2 4 2 0 0 3 1 4 1 0 5 3 4 2 1 2 0 1 1 1 2 3 2 1 0 4 1 2 3 3 2 3 2 1
 loss 1.58 top1 46.600002 top5 92.000000
Traceback (most recent call last):
  File "/home/env/lib/python3.6/multiprocessing/util.py", line 262, in _run_finalizers
    finalizer()
  File "/home/env/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/env/lib/python3.6/shutil.py", line 490, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/home/env/lib/python3.6/shutil.py", line 488, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/tmp/pymp-w8qkrgdb'

**Comment by d12306** [comment]
@kl2005ad , @HKLee2040 , it seems like the program can still running after this error, does this error affect the final acc?

**Comment by smeenap** [comment]
Any update on this? it seems like the program can still run after this error, does this error affect the final result?
